export const healthQuestions = [
  { number: 1, text: '¿Fue atendido por un médico últimamente?', detailLabel: '¿Hace qué tiempo?', extraLabel: '¿Cuál fue la razón?' },
  { number: 2, text: '¿Ha tenido Ud. un problema de tipo cardiaco?', detailLabel: '¿Qué tipo?' },
  { number: 3, text: '¿Ha tenido Ud. un problema de tipo renal?', detailLabel: '¿Qué tipo?' },
  { number: 4, text: '¿Ha tenido Ud. un problema de tipo pulmonar?', detailLabel: '¿Qué tipo?' },
  { number: 5, text: '¿Ha tenido Ud. un problema de tipo gástrico?', detailLabel: '¿Qué tipo?' },
  { number: 6, text: '¿Ha tenido Ud. alguna alteración del SNC?', detailLabel: '¿Qué tipo?' },
  { number: 7, text: '¿Ha tenido Ud. un problema de tipo digestivo?', detailLabel: '¿Qué tipo?' },
  { number: 8, text: '¿Ha tenido Ud. un problema en el sistema hepático (Hepatitis)?', detailLabel: '¿Qué tipo?' },
  { number: 9, text: '¿Ha tenido Ud. un problema de hipertensión?', detailLabel: '¿Qué tipo?' },
  { number: 10, text: '¿Ha tenido Ud. alguna vez una enfermedad venérea?', detailLabel: '¿Qué tipo?' },
  { number: 11, text: '¿Ha tenido Ud. un trastorno de tipo tiroideo?', detailLabel: '¿Qué tipo?' },
  { number: 12, text: '¿Ha tenido Ud. alguna vez pápulas o hipersensibilidades?', detailLabel: '¿Qué tipo?' },
  { number: 13, text: '¿Es Ud. alérgico a la penicilina?', detailLabel: 'Detalle' },
  { number: 14, text: '¿Es Ud. alérgico a otro tipo de medicamento?', detailLabel: '¿Qué tipo?' },
  { number: 15, text: '¿Ha sido internado alguna vez en un hospital?', detailLabel: '¿Qué causa?' },
  { number: 16, text: '¿Le han realizado alguna vez transfusión sanguínea?', detailLabel: '¿Qué tipo?' },
  { number: 17, text: '¿Ud. tiene algún problema con las articulaciones óseas?', detailLabel: '¿Qué tipo?' },
  { number: 18, text: '¿Ud. tiene algún problema hematológico?', detailLabel: '¿Con qué?' },
  { number: 19, text: '¿Ha sufrido algún tipo de desmayo o convulsiones?', detailLabel: '¿Qué tipo?' },
  { number: 20, text: '¿Ud. sufre o tiene diabetes?', detailLabel: '¿Qué tipo?' },
  { number: 21, text: 'Si tiene Ud. diabetes, ¿está compensado?', detailLabel: 'Detalle' },
  { number: 22, text: '¿Ud. tiene o presentó algún problema en la piel?', detailLabel: '¿Qué tipo?' },
  { number: 23, text: '¿Tiene o presenta un proceso infeccioso o respiratorio?', detailLabel: '¿Qué tipo?' },
  { number: 24, text: '¿Tiene o presenta una dificultad para respirar?', detailLabel: '¿Qué tipo?' },
];
